apiVersion: v1
kind: Service
metadata:
  labels:
    pod-name: m1-replica-set-0
  name: m1-replica-set-svc-ext
  namespace: mongodb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    pod-name: m1-replica-set-0
  sessionAffinity: None
  type: LoadBalancer
