apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: m2-sharded-cluster
  namespace: mongodb
spec:
  shardCount: 2
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 3
  version: 4.2.3-ent
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: om-main-user-credentials
  type: ShardedCluster
  persistent: true
