apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  # the version of Ops Manager distro to use
  version: 4.2.4
  # the name of the secret containing admin user credentials.
  adminCredentials: ops-manager-admin-secret
  # use LoadBalancer is your K8s infrastructure supports it
  externalConnectivity:
    type: NodePort
  # disable backups since this is a dev deploy
  backup:
    enabled: false
  # the Replica Set backing Ops Manager.
  # appDB has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
    version: 4.2.3
