apiVersion: v1
kind: Service
metadata:
  name: m0-standalone-svc-ext
  namespace: mongodb
  labels:
    app: m0-standalone-svc
    provider: aws
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: m0-standalone-svc
  sessionAffinity: None
  type: LoadBalancer
