apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mongodb-default-storageclass
  local:
    path: /data/mongodb-standalone # has to exist on worker node
  nodeAffinity:
    required:
      nodeSelectorTerms: # choose a nodeSelector
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - kubeone
