apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-default-storageclass
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms: # choose a nodeSelector
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - kubeone
