kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc64gb
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
