apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: m1-replica-set
  namespace: mongodb
  labels:
    provider: gcp  
spec:
  members: 3
  version: 4.2.3-ent
  type: ReplicaSet
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: om-main-user-credentials
